#텍스트데이터분석_01_Numpy

##1. 넘파이 설치 확인

In [31]:
import numpy as np
print(np.__version__)

2.3.5


#2. 넘파이 배열(ndarray) 생성과 속성 확인


In [32]:
a1 = np.array([1,2,3])
print(a1, type(a1), a1.dtype, a1.ndim, a1.shape, a1.size)
a2 = np.array([1,2,3])
print(a2, type(a2), a2.dtype, a2.ndim, a2.shape, a2.size)

[1 2 3] <class 'numpy.ndarray'> int64 1 (3,) 3
[1 2 3] <class 'numpy.ndarray'> int64 1 (3,) 3


In [33]:
a3 = np.array([[1,2,3], [4,5,6]])
print(a3)
print(type(a3), a3.dtype, a3.ndim, a3.shape, a3.size)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'> int64 2 (2, 3) 6


In [34]:
a1 = np.array([1,2,3], dtype = float)
print(a1, type(a1), a1.dtype, a1.ndim, a1.shape, a1.size)


[1. 2. 3.] <class 'numpy.ndarray'> float64 1 (3,) 3


In [35]:
a6 = np.array([1, 4, 5, '8'])
print(a6)
print(type(a6), a6.dtype, a6.ndim, a6.shape, a6.size)

['1' '4' '5' '8']
<class 'numpy.ndarray'> <U21 1 (4,) 4


In [36]:
test_list = [[1, 4, 5, 8], [1, 4, 5]]
np.array(test_list, float)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

3. Indexing

In [37]:
d3 = np.arange(12).reshape(2, 2, 3)
print(d3)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [38]:
d3[0] = 50
d3

array([[[50, 50, 50],
        [50, 50, 50]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

4. Slicing

In [39]:
d3[1,0] = 30
print(d3)

[[[50 50 50]
  [50 50 50]]

 [[30 30 30]
  [ 9 10 11]]]


In [40]:
import numpy as np
d=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(d)
print(d[2:3], d[:], d[:-1])
print(d[::2], d[::-1])

[1 2 3 4 5 6 7 8 9]
[3] [1 2 3 4 5 6 7 8 9] [1 2 3 4 5 6 7 8]
[1 3 5 7 9] [9 8 7 6 5 4 3 2 1]


In [41]:
d2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(d2[0]) # 0행만 슬라이싱
print(d2[0,:]) # 0행의 전체 열 슬라이싱
print(d2[:,:-1]) # 마지막 열 제외한 전체 행과 열 슬라이싱
print(d2[::2,::2]) # 2행 2열 간격으로 전체 행과 열 슬라이싱

[1 2 3 4 5]
[1 2 3 4 5]
[[1 2 3 4]
 [6 7 8 9]]
[[1 3 5]]


In [42]:
d3 = np.arange(12).reshape(2, 2, 3)
print(d3)
print(d3[:,:-1,:-1])
print(d3[:,1:,1:])
print(d3[:,:,-1])
print(d3[:,-1,-1])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[0 1]]

 [[6 7]]]
[[[ 4  5]]

 [[10 11]]]
[[ 2  5]
 [ 8 11]]
[ 5 11]


In [43]:
d2 = np.arange(1,11).reshape(2,-1)
print(d2)
d2[1:, :] = -1
print(d2)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [-1 -1 -1 -1 -1]]


In [44]:
#전체 요소값을 한꺼번에 변경
d2[:,:] = -1
print(d2)

[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


5. Boolean Indexing (불 인덱싱)

In [45]:
data = np.array([4, 6, 7, 3, 2, 0])
print(data > 3)
print(data[data > 3])

[ True  True  True False False False]
[4 6 7]


In [46]:
data = np.array([4, 6, 7, 3, 2, 0])
# 2보다 크고 6보다 작은 요소만 추출
print(data[(data > 3) & (data < 6)])
# 짝수만 출력
print(data[data % 2 ==0])
# 평균보다 작은 값만 추출
print(data[data < data.mean( )])

[4]
[4 6 2 0]
[3 2 0]


펜시 인덱싱 (Fancy indexing)

In [47]:
f= np.array([4, 6, 7, 3, 2])
indexes = np.array([1, 2, 0, 2, 2, 2])
f[indexes]

array([6, 7, 4, 7, 7, 7])

In [48]:
f2 = np.array([[1, 4], [9, 16]])
x = np.array([0, 1, 1, 1, 0, 0])
y = np.array([0, 0, 0, 1, 1, 1])
f2[x,y]

array([ 1,  9,  9, 16,  4,  4])

6. 넘파이 배열의 정렬

In [49]:
numbers = np.array([2, 8, 9, 7, 3, 1, 4, 5, 6])
sorted_numbers = np.sort(numbers)
print(numbers)
print(sorted_numbers)
print(sorted_numbers[::-1])

[2 8 9 7 3 1 4 5 6]
[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


In [50]:
numbers.sort()
print(numbers)

[1 2 3 4 5 6 7 8 9]


In [51]:
arr2d = np.array([[5, 6, 7, 8],[4, 3, 2, 1],[10, 9, 12, 11]])
print(arr2d)


[[ 5  6  7  8]
 [ 4  3  2  1]
 [10  9 12 11]]


In [52]:
print(np.sort(arr2d))
print(np.sort(arr2d, axis = 1))
print(np.sort(arr2d, axis = 0))


[[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]
[[ 4  3  2  1]
 [ 5  6  7  8]
 [10  9 12 11]]


In [53]:
numbers = np.array([2, 8, 9, 7, 3, 1, 4, 5, 6])
sorted_indexes = np.argsort(numbers)
print(sorted_indexes)


[5 0 4 6 7 8 3 1 2]


In [54]:
# [연습문제] 성적 순으로 출력(내림차순)
names = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
scores = np.array([78, 95, 84, 98, 88])


In [55]:
scores_sorted_index = np.argsort(scores)[::-1]
print(scores_sorted_index)
print(names[scores_sorted_index])


[3 1 4 2 0]
['Kate' 'Mike' 'Samuel' 'Sarah' 'John']


In [56]:
scores_sorted_index = np.argsort(scores)[::-1]
print(scores_sorted_index)
print(names[scores_sorted_index])

[3 1 4 2 0]
['Kate' 'Mike' 'Samuel' 'Sarah' 'John']


any(), all() 함수의 활용

In [57]:
# 1. 배열에 결측치가 하나라도 포함되어 있는지 확인
data = np.array([1, 2, np.nan, 4])
print(np.any(np.isnan(data))) # True


True


In [58]:
# 2. 두 배열이 완전히 동일한지 확인
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
print(np.all(arr1 == arr2)) # True (요소별 비교 후 전체 확인)

True
